version: "3"

services:

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.2.2'
    expose:
      - '2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: 'confluentinc/cp-kafka:7.2.2'
    expose:
      - '9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'
    volumes:
      - ./scripts/kafka-read-topic:/usr/local/bin/read-topic
    depends_on:
      - zookeeper

  # https://stackoverflow.com/a/69534299/2071807
  init-kafka:
    image: 'confluentinc/cp-kafka:7.2.2'
    depends_on:
      - kafka
    environment:
      TOPICS: 'wind solar'
    entrypoint: [ '/bin/sh', '-f' ]
    command: '/var/scripts/init-kafka.sh'
    volumes:
      - ./scripts/:/var/scripts

  weather:
    build:
      context: .
      dockerfile: weather.Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:29092'
      PYTHONPATH: '/app'
    volumes:
      - ./weather:/app/weather
      - ./scripts:/app/scripts
    command: 'scripts/do-nothing'
